p8105_hw2_mbc2178
================
Melvin Coleman
2022-10-02

Let’s load in the libraries needed to perform data manipulation and
cleaning for this assignment.

``` r
library(tidyverse)
```

    ## ── Attaching packages ─────────────────────────────────────── tidyverse 1.3.2 ──
    ## ✔ ggplot2 3.3.6      ✔ purrr   0.3.4 
    ## ✔ tibble  3.1.8      ✔ dplyr   1.0.10
    ## ✔ tidyr   1.2.0      ✔ stringr 1.4.1 
    ## ✔ readr   2.1.2      ✔ forcats 0.5.2 
    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()

``` r
library(dplyr)
library(readxl)
library(readr)
```

## Problem 1

Below we import the csv file containing NYC transit data
`NYC_Transit_Subway_Entrance_And_Exit_Data.csv`. We first import our
dataset to R and perform data cleaning and manipulations to fit the
assignment. We keep the variables `station`, `name`,
`station latitude/longitude`, `routes`, `entry`, `vending`,
`entrance type`, and `ada`. In addition, we convert the variable `entry`
from character to a logical variable.

``` r
nyc_transit_df = 
    read_csv(
      file = "./data/NYC_Transit_Subway_Entrance_And_Exit_Data.csv",
      col_types = cols(Route8 = "c", Route9 = "c", Route10 = "c", Route11 = "c")) %>%
     janitor::clean_names() %>%
    select(
      line, station_name, station_latitude, station_longitude, starts_with("route"),
      entry, vending,  exit_only, vending, entrance_type, ada) %>%
    mutate(entry = ifelse(entry == "YES", TRUE, FALSE))
```

After completing the cleaning procedure above, the data still doesn’t
look tidy. There are 1868and 20. The variables `route8 - route11` were
changed to character variables and the variable `entry` was changed to a
logical variable.

The variables in our dataset include `line`, `station_name`,
`station_latitude`, `station_longitude`, `route1 - route11`,`entry`,
`vending`, `exit_only`, `vending`, `entrance_type` and `ada`.

We will need to perform additional manipulations on variables
`route1-route11` to ensure that there is one variable that contains all
of the subway routes.

The code chunk below selects the station names and line numbers to
determine the number of distinct stations. We use the `select` function
to select `station_name` and `line` and use the `distinct` function to
only select a unique station per row in our data frame.

``` r
nyc_transit_df %>% 
  select(station_name, line) %>% 
  distinct
```

    ## # A tibble: 465 × 2
    ##    station_name             line    
    ##    <chr>                    <chr>   
    ##  1 25th St                  4 Avenue
    ##  2 36th St                  4 Avenue
    ##  3 45th St                  4 Avenue
    ##  4 53rd St                  4 Avenue
    ##  5 59th St                  4 Avenue
    ##  6 77th St                  4 Avenue
    ##  7 86th St                  4 Avenue
    ##  8 95th St                  4 Avenue
    ##  9 9th St                   4 Avenue
    ## 10 Atlantic Av-Barclays Ctr 4 Avenue
    ## # … with 455 more rows

There are 465 distinct stations in the `nyc_transit_df`(the number of
rows in the table are 465).

Next, we determine the number of stations that are ADA compliant in this
dataframe. We first use the `filter` function to filter out only
stations that are ADA compliant and select the unique station and line
in the subway system per row.

``` r
nyc_transit_df %>% 
  filter(ada == "TRUE") %>% 
  select(station_name, line) %>% 
  distinct()
```

    ## # A tibble: 84 × 2
    ##    station_name                   line           
    ##    <chr>                          <chr>          
    ##  1 Atlantic Av-Barclays Ctr       4 Avenue       
    ##  2 DeKalb Av                      4 Avenue       
    ##  3 Pacific St                     4 Avenue       
    ##  4 Grand Central                  42nd St Shuttle
    ##  5 34th St                        6 Avenue       
    ##  6 47-50th Sts Rockefeller Center 6 Avenue       
    ##  7 Church Av                      6 Avenue       
    ##  8 21st St                        63rd Street    
    ##  9 Lexington Av                   63rd Street    
    ## 10 Roosevelt Island               63rd Street    
    ## # … with 74 more rows

There are 84 stations that are ADA compliant in the `nyc_transit_df`
data frame (the number of rows in this tibble is 84).

Now we determine the proportion of station entrances/ exits without
vending allow entrance. We exclude stations that do that allow vending
by using the `filter` function. Then we use the `pull` function on
`entry` to find the mean of this logical variable. This mean will tell
us the proportion of station entrances/exists without vending allow
entrance.

``` r
nyc_transit_df %>%
  filter(vending == "NO") %>% 
  pull(entry) %>% 
  mean
```

    ## [1] 0.3770492

There are 37.7% of station entrances/exits without vending allow
entrance (mean from code chunk output above).

Last, we now reformat our data so that the route number and route name
are distinct variables. We use the `pivot_longer` to transform the
variables to rows. Then we filter to select only the A train and use the
`distinct function` to select unique stations that serve the A train and
the number that are ADA compliant.

``` r
nyc_transit_df %>%
  pivot_longer(
    route1:route11,
    names_to = "route_num",
    values_to = "route") %>% 
  filter(route == "A") %>%
select(station_name,line)%>%
distinct()
```

    ## # A tibble: 60 × 2
    ##    station_name                  line           
    ##    <chr>                         <chr>          
    ##  1 Times Square                  42nd St Shuttle
    ##  2 125th St                      8 Avenue       
    ##  3 145th St                      8 Avenue       
    ##  4 14th St                       8 Avenue       
    ##  5 168th St - Washington Heights 8 Avenue       
    ##  6 175th St                      8 Avenue       
    ##  7 181st St                      8 Avenue       
    ##  8 190th St                      8 Avenue       
    ##  9 34th St                       8 Avenue       
    ## 10 42nd St                       8 Avenue       
    ## # … with 50 more rows

``` r
nyc_transit_df %>%
   pivot_longer(
    route1:route11,
    names_to = "route_num",
    values_to = "route") %>% 
  filter(route =="A", ada =="TRUE") %>%
select(station_name,line) %>%
distinct()
```

    ## # A tibble: 17 × 2
    ##    station_name                  line            
    ##    <chr>                         <chr>           
    ##  1 14th St                       8 Avenue        
    ##  2 168th St - Washington Heights 8 Avenue        
    ##  3 175th St                      8 Avenue        
    ##  4 34th St                       8 Avenue        
    ##  5 42nd St                       8 Avenue        
    ##  6 59th St                       8 Avenue        
    ##  7 Inwood - 207th St             8 Avenue        
    ##  8 West 4th St                   8 Avenue        
    ##  9 World Trade Center            8 Avenue        
    ## 10 Times Square-42nd St          Broadway        
    ## 11 59th St-Columbus Circle       Broadway-7th Ave
    ## 12 Times Square                  Broadway-7th Ave
    ## 13 8th Av                        Canarsie        
    ## 14 Franklin Av                   Franklin        
    ## 15 Euclid Av                     Fulton          
    ## 16 Franklin Av                   Fulton          
    ## 17 Howard Beach                  Rockaway

There are 60 stations that serve the A train and 17 stations re ADA
compliant in the `nyc_transit_df` dataframe.

## Problem 2

Let’s load the `readxl` library to import the excel sheet containing
data for Mr. Trash Wheel dataset. We will clean this dataset by
ommitting non-data entries using arguments in the `read_excel` function.
Then we will round variable `sports_balls` to the nearest integer using
`as.integer`. We will perform a similar process on the excel sheet
containing data for Professor Trash Wheel.

After data cleaning, we will combine the two datasets to produce a
single tidy dataset. We will create a unique variable called `loc_trash`
to keep track of which Trash Wheel is which. New combined data frame
arranged in ascending order.

``` r
trash_df = 
  read_excel("data/Trash Wheel Collection Data.xlsx", sheet = "Mr. Trash Wheel", 
             range = "A2:N549", na = "", col_names = TRUE, col_types = NULL) %>%
  janitor::clean_names() %>% 
  drop_na() %>% 
  mutate(
    sports_balls = as.integer(round(sports_balls, digits= 0)), 
   loc_trash = "Mr. Trash Wheel",
   year = as.numeric(year)
   ) 
   
proftrsh_df =
  read_excel("data/Trash Wheel Collection Data.xlsx", sheet = "Professor Trash Wheel",
             range = "A2:M96", na = "", col_names = TRUE, col_types = ) %>% 
janitor::clean_names() %>% 
  drop_na() %>% 
  mutate(
   loc_trash = "Professor Trash Wheel"
   )
```

``` r
tidy_trash =
  bind_rows(trash_df, proftrsh_df) %>% 
  janitor::clean_names() %>% 
  arrange()
```

Now that we have cleaned our data frame we have a tidy dataset called
`tidy_trash` from combining `trash_df` and `proftrsh_df`. In this new
data frame, `tidy_trash` there are 568 observations and 15 variables.
Some of these variables include:

    ## tibble [568 × 15] (S3: tbl_df/tbl/data.frame)
    ##  $ dumpster          : num [1:568] 1 2 3 4 5 6 7 8 9 10 ...
    ##  $ month             : chr [1:568] "May" "May" "May" "May" ...
    ##  $ year              : num [1:568] 2014 2014 2014 2014 2014 ...
    ##  $ date              : POSIXct[1:568], format: "2014-05-16" "2014-05-16" ...
    ##  $ weight_tons       : num [1:568] 4.31 2.74 3.45 3.1 4.06 2.71 1.91 3.7 2.52 3.76 ...
    ##  $ volume_cubic_yards: num [1:568] 18 13 15 15 18 13 8 16 14 18 ...
    ##  $ plastic_bottles   : num [1:568] 1450 1120 2450 2380 980 1430 910 3580 2400 1340 ...
    ##  $ polystyrene       : num [1:568] 1820 1030 3100 2730 870 2140 1090 4310 2790 1730 ...
    ##  $ cigarette_butts   : num [1:568] 126000 91000 105000 100000 120000 90000 56000 112000 98000 130000 ...
    ##  $ glass_bottles     : num [1:568] 72 42 50 52 72 46 32 58 49 75 ...
    ##  $ grocery_bags      : num [1:568] 584 496 1080 896 368 ...
    ##  $ chip_bags         : num [1:568] 1162 874 2032 1971 753 ...
    ##  $ sports_balls      : int [1:568] 7 5 6 6 7 5 3 6 6 7 ...
    ##  $ homes_powered     : num [1:568] 0 0 0 0 0 0 0 0 0 0 ...
    ##  $ loc_trash         : chr [1:568] "Mr. Trash Wheel" "Mr. Trash Wheel" "Mr. Trash Wheel" "Mr. Trash Wheel" ...

The total weight of trash collected by Professor Trash Wheel was
162.54tons. On the other hand, the total number of sports balls
collected by Mr. Trash Wheel in 2020 was 856.

## Problem 3

First, we import the `pols-month.csv` excel sheet and clean this data
frame. We use `separate ()` to break the variable `mon` into `year`,
`month` and `day` variables. Because we want our variable `month` to be
month names, we use the `mutate` function and apply a `month.name` to
change the numeric number of months to names. In addition, we use an
`if_else` statement to produce variable `president` transforming the
values of `prez_dem` and `prez_gop` to character strings under just this
one variable. `Day`, `prez_dem`, and `prez_gop` were removed from data
frame.

We perform similar processes on data in `snp.csv` and
`unemployment data`. Columns are arranged according to `year` and
`month` as leading columns in `snp.csv` and `pols-month.csv`.

``` r
pols_month = 
  read_csv("./data/fivethirtyeight_datasets/pols-month.csv") %>% 
  janitor::clean_names() %>% 
  separate(mon, into = c("year", "month", "day")) %>% 
  mutate(
      month= month.name[as.numeric(month)],
      year = as.numeric(year),
     
       president = if_else(
      prez_dem == 1, "dem",
      if_else(
        prez_gop > 0, "gop", ""
      )
    )
  ) %>%
  select (-prez_dem, -prez_gop, -day)
```

    ## Rows: 822 Columns: 9
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl  (8): prez_gop, gov_gop, sen_gop, rep_gop, prez_dem, gov_dem, sen_dem, r...
    ## date (1): mon
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
snp_df = 
  read_csv("./data/fivethirtyeight_datasets/snp.csv") %>% 
  janitor::clean_names() %>% 
  separate(date, into = c("month", "day", "year")) %>% 
  mutate(
      month= month.name[as.numeric(month)],
      year = as.numeric(year),
      
       year = if_else(
         year > 22, 1900 + year,
         2000 + year)
       ) %>% 
  select(year, month, close)
```

    ## Rows: 787 Columns: 2
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (1): date
    ## dbl (1): close
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

Now let’s tidy the `unemployment data` so that it can be merged with the
`pols-month` and `snp_df`. We first import the data and clean using the
`janitor` function and convert the columns with month names to one
variable `month`. The values of the rows will be transferred to one
variable called `percent_unemply`. The values of the `month` variable
are abbreviated so we transformed this to fit the style of the previous
data frames above.

``` r
unemply_df = 
  read_csv("./data/fivethirtyeight_datasets/unemployment.csv") %>%
  janitor::clean_names() %>% 
  pivot_longer(
    jan:dec,
    names_to = "month",
    values_to = "percent_unemply"
  ) %>%
  mutate(
    month = (str_to_title(month)) %>%  
  factor(month, levels = month.abb, 
        labels = month.name))
```

    ## Rows: 68 Columns: 13
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl (13): Year, Jan, Feb, Mar, Apr, May, Jun, Jul, Aug, Sep, Oct, Nov, Dec
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

Now we have imported, cleaned and tidied all three of our data
(`pols-month`, `snp_df` & `unemply_data`) containing number of
politicians who are democratic or republican, representative measure of
stock market as a whole and unemployment respectively.

We will now proceed to merge data from `pols-month` and `snp-df`. After
that, we will merge the result to `unemply-data`. We will perform a
right join first, merging `snp_df` into `pols_month` and then a left
join, merging `unemply_df` into the result.

``` r
rightmrg_df = 
  right_join(snp_df, pols_month, by = c("year", "month"))

leftmrg_df =
  left_join(rightmrg_df, unemply_df, by =c("year", "month"))
```
